name: lbm

# Triggers testing
on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-23.04

    steps:
    - uses: actions/checkout@v4.1.1
    - name: Set-up python
      uses: actions/setup-python@v4.7.1
      with:
        python-version: 3.12
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install -r requirements.txt
    - name: Test with pytest
      run: |
        pytest
